### ISSUE TITLE
Update deprecated HLJS Function

### ISSUE THREAD

**Issue by tdrayson** [srikat/WP-HighlightJS#3]
```Deprecated as of 10.6.0. initHighlightingOnLoad() deprecated.  Use highlightAll() now.```

<img width="1680" alt="Screenshot 2021-08-19 at 20 58 46" src="https://user-images.githubusercontent.com/33532995/130135764-6711e20a-8cd8-4d83-9c09-4169148f0fb9.png">

Change line 61 in `assets/js/highlight-init.js` to:

```hljs.highlightAll();```

**Comment by srikat** [comment]
Updated, ty.
